name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '3.2', '3.3', 'head' ]
        rails: [ '7.1', 'edge' ]
        include:
          - ruby: '2.7'
            rails: '6.1'
          - ruby: '3.0'
            rails: '6.1'
          - ruby: '3.1'
            rails: '7.0'

    env:
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run unit tests
        run: bundle exec rake test:unit
        timeout-minutes: 3

      - name: Run acceptance tests
        run: bundle exec rake test:acceptance
        timeout-minutes: 10
        if: ${{ matrix.rails != 'edge' && matrix.ruby != 'head' }} # Acceptance tests use `gem install rails && rails new`
